# Port du serveur
server.port=8089

# --- CONFIGURATION POSTGRESQL (DOCKER) ---
# On remplace H2 par l URL de ton conteneur Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driverClassName=org.postgresql.Driver

# --- JPA / HIBERNATE ---
# Update : cree les tables automatiquement au premier lancement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- SECURITE ---
# Identifiants temporaires pour ton developpement
spring.security.user.name=admin
spring.security.user.password=1234

# --- H2 CONSOLE (A DESACTIVER) ---
# On le met a false car on n utilise plus H2
spring.h2.console.enabled=false